service: historical-figures-whisper-bot

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-west-3
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}

functions:
  historicalFiguresTelegramBot:
    handler: main.main
    events:
        - eventBridge:
          schedule: rate(1 day)
    timeout: 60 # seconds
    memorySize: 256 # mb
    description: historical-figures-whisper-bot

package:
  individually: true