service: historical-figures-whisper-bot

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-west-3
  versionFunctions: false
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}

functions:
  webhook:
    handler: src.main.lambda_handler
    events:
      - http:
          path: /
          method: POST
          cors: true
    timeout: 30 # seconds
    memorySize: 256 # mb
    description: webhook to trigger the Historical Figures Whisper Telegram Bot

package:
  individually: true

plugins:
  - serverless-python-requirements
